name: uis
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.8
  nb_utils: ^7.2.0
  intl: ^0.20.2
  flutter_vector_icons: ^2.0.0
  google_fonts: ^8.0.0

  # Common
  share_plus: ^10.0.0
  url_launcher: ^6.2.6
  http: ^1.6.0
  html: ^0.15.5
  package_info_plus: ^8.0.0

  # State management
  mobx: ^2.3.5
  flutter_mobx: ^2.2.0

  # Map
  google_maps_flutter: ^2.6.0

  # UI
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - images/
